### ISSUE TITLE
lessPlugins ignored, potential fix

### ISSUE THREAD

**Issue by bazineta** [webpack-contrib/less-loader#161]
Original discussion on this can be found toward the end of #115.

In 3.0.0, `lessPlugins` option as documented in the README doesn't appear to actually do anything.

If I instead specify less plugins in `plugins`, the `cloneDeep()` call in the loader's options processing will wipe the `install` function from each plugin, and a `plugin.install is not a function` will be emitted during processing.

What seems to work, assuming that lessPlugins is the desired approach, is adding this:
```
if (options.lessPlugins) {
    options.plugins.push.apply(options.plugins, loaderUtils.getOptions(this).lessPlugins);
}
```
immediately after the line:
```
options.plugins.push(webpackPlugin);
```
In the loader.

I'd guess that `cloneDeep()` might not actually be what's desired here, but this approach matches the README.

**Comment by bazineta** [comment]
@jhnns If this makes sense, or if I'm off base here but could address this some other way, please let me know -- quite happy to submit a PR if this is appropriate.

**Comment by jhnns** [comment]
Thx, I'll take a look in the next days. The documentation might be out of date, have to check that.

**Comment by kfeinUI** [comment]
Confirmed. The suggested fix seems to do the trick.

**Comment by jhnns** [comment]
This should be fixed with less-loader 4. We have a [test for it](https://github.com/webpack-contrib/less-loader/blob/53c90fcd39ceba4121f57971d3f5666a0b1abc34/test/index.test.js#L184-L195).

We're still using `cloneDeep()`, so I'm not sure what has changed. But the test is running...

**Comment by bazineta** [comment]
@jhnns Well, I'd love to test it out, but at present 4.0.0 has a 'dist/cjs.js' in the package.json, which doesn't exist, so it won't run.

**Comment by bazineta** [comment]
@jhnns However, assuming something along the lines of index.js is what's needed there, it still won't run, and it fails with the same 'install isn't a function' error. I have no idea how your test case could be running; cloneDeep() will destroy any function present, period.

**Comment by bazineta** [comment]
@jhnns The same fix works in this case; in getOptions.js:
```
options.filename = loaderContext.resource;

  if (options.lessPlugins) {
      options.plugins.push.apply(options.plugins, loaderUtils.getOptions(loaderContext).lessPlugins);
  }
```
Note that I've used the old 'lessPlugins' key here, as cloneDeep() will have damaged what's in 'plugins' beyond the ability to easily use at this point.
